Add patch for 'Perl_fp_class_denorm'
Patch error:
    sv.o: In function `S_hextract':
    sv.c:(.text+0xcfd): undefined reference to `Perl_fp_class_denorm'

perl5 commit message:
    Fallbacks for Perl_fp_class_denorm().

        These may be needed if the compiler doesn't expose the C99 math
        without some special switches.

See also:
- https://rt.perl.org/Public/Bug/Display.html?id=132255
- perl5 commit 488307ffa67ce70fc9755e560a74dac04bdcb0e4